application: bram-fsnd
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  script: main.app

- url: /index\.html
  script: main.app

- url: /css
  static_dir: css

- url: /(.*\.(gif|png|jpg|svg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg|svg)$

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest

