application: bram-fsnd
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /sign-up
  script: handlers.access.app

- url: /blog/sign-up
  script: handlers.access.app

- url: /blog/registration
  script: handlers.access.app

- url: /blog/login
  script: handlers.access.app

- url: /blog/.*/.*
  script: handlers.blog.app

- url: /blog/.*
  script: handlers.blog.app

- url: /blog
  script: handlers.blog.app

- url: /rot13
  script: handlers.rot13.app

- url: /ascii
  script: handlers.ascii_art.app

- url: /
  script: handlers.main.app

- url: /index\.html
  script: handlers.main.app

- url: /css
  static_dir: css

- url: /(.*\.(gif|png|jpg|svg|jpeg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg|svg|jpeg)$

- url: .*
  script: handlers.main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
